### ISSUE TITLE
@varlet/touch-emulator，在桌面端体验不友好

### ISSUE THREAD

**Issue by yexiaodong** [haoziqaq/varlet#114]
安装@varlet/touch-emulator，并在main.js中导入：
`
import '@varlet/touch-emulator'
`

但是切换效果不理想：
希望效果：按住鼠标左键滑动时，切换
当前效果：按住鼠标左键滑动，然后松开，再次滑动才切换

**Comment by haoziqaq** [comment]
pc文档右侧手机的部分就是通过这个包进行适配的结果，swipe的效果是你期望的效果么？

**Comment by haoziqaq** [comment]
方便的话能否提供一个问题demo，可以发到我的邮箱。

**Comment by yexiaodong** [comment]
测试例子：https://gitee.com/yexiaodong/do-vue-simple

**Comment by yexiaodong** [comment]
是要PC文档右侧手机部分的效果

**Comment by haoziqaq** [comment]
您是mac电脑么

**Comment by haoziqaq** [comment]
如果您是mac电脑，img标签的图像在拖动时会有默认行为，会导致您现在出现的问题，touchmove事件被默认行为打断了
如下可以解决，如果是这个问题，就不是很好在某个组件里规避了，需要用户自行解决。

以下是您给出的demo下面的代码

```css
.swipe-item {
  width: 100%;
  height: 100%;
  object-fit: cover;
  加入这行代码
  pointer-events: none;
}
```
